package org.improsokk.helyszin;

public enum Helyszinek {
    RUHABOLT("Ruha bolt"),
    GYOGYSZERTAR("Gyogyszertar"),
    ISKOLA("Iskola"),
    HAJO("Hajo fedelzet"),
    ASATAS("Asatas"),
    VONATON("Vonaton"),
    KONCERT("Koncert"),
    VIZALATTI_BAZIS("Viz alatti bazis"),
    KONYVTAR("Konyvtar"),
    GYAR("Gyar"),
    MOZI("Mozi"),
    KOCSMA("Kocsma"),
    HENTES("Hentes"),
    REGISEGKERESKEDES("Regisegkereskedes"),
    BAR("Bar"),
    JATEKBOLT("Jatekbolt"),
    OTTHON("Otthon"),
    ETTEREM("Etterem"),
    LAKATLAN_SZIGET("Lakatlan sziget"),
    TUNTETES("Tuntetes"),
    AUTOMOSO("Auto moso"),
    AUTOS_OKTATAS("Autos oktatas"),
    BARLANG("Barlang"),
    KONFERENCIA("Konferencia"),
    VIDEOTEKA("Videoteka"),
    SZORAKOZOHELY("Szorakozohely"),
    ESKUVO("Eskuvo"),
    LABORATORIUM("Laboratorium"),
    PIAC("Piac"),
    KORHAZ("Korhaz"),
    PARK("Park"),
    JATSZOTER("Jatszoter"),
    KIKOTO("Kikoto"),
    REPULOTER("Repuloter"),
    CUKRASZDA("Cukraszda"),
    BUSZMEGALLO("Buszmegallo"),
    PLEBANIA("Plebania"),
    MENZA("Menza"),
    ALULJARO("Aluljaro"),
    VERSENY("Verseny"),
    KONDITEREM("Konditerem"),
    LOVARDA("Lovarda"),
    BETORES("Betores"),
    LAKTANYA("Laktanya"),
    URALLOMAS("Urallomas"),
    BALESETI_HELYSZIN("Baleseti helyszin"),
    EPITKEZES("Epitkezes"),
    TALKSHOW("Talkshow"),
    TERAPEUTANAL("Terapeutanal"),
    FONOKI_IRODA("Fonoki iroda"),
    ALLASINTERJU("Allasinterju"),
    UTAZASI_IRODA("Utazasi iroda"),
    ORVOSI_RENDELO("Orvosi rendelo"),
    TEMETES("Temetes"),
    FOTOZAS("Fotozas"),
    RENDORSEG("Rendorseg"),
    VADNYUGAT("Vadnyugat"),
    VADASZAT("Vadaszat"),
    FOGASZAT("Fogaszat"),
    ZENEBOLT("Zene bolt");

    public String helyszin;
    Helyszinek(String helyszin){
        this.helyszin=helyszin;
    }


}
